trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isGlobal: 'true'

stages:
- stage: First
  displayName: Build Stage
  jobs:
  - job: Firstjob
    displayName: BuildFirst
    timeoutInMinutes: 10
    variables:
      isStage1: 'isStage1'
    steps:
    - task: Bash@3
      displayName: First echo-Master branch
      inputs:
        targetType: 'inline'
        script: |
          echo "The First job in Master branch";
          echo $(Build.Reason)
          echo "isStage1-"$(isStage1)
          echo "isGlobal-"$(isGlobal)
          echo "isFourth-"$(isFourth)
- stage: Second
  displayName: Deploy to Env1
  variables:
  - group: vg1
  dependsOn: 'First'
  jobs:  
  - job: Secondjob
    displayName: Deploy2Test
    steps:
    - bash: echo "Our Second Pipeline" ; echo "vg1-"$(v1)
- stage: Third
  displayName: SanityCheck Stage
  dependsOn: Second
  jobs:  
  - job: Thirdjob
    displayName: FuncSanityAfterDeploy
    steps:
    - bash: echo "Our Third Pipeline"
  - job: PerfJob
    displayName: Early Performance Sanity
    steps:
    - bash: echo "Our Early Performance Sanity"

- stage: Fourth
  displayName: 'Deploy in PT env Stage'
  dependsOn: Third
  condition: and(succeeded(), eq(variables.isMain, true))
  jobs:  
  - job: Deploy4Performance
    displayName: Deploy4Performance
    steps:
    - bash: echo "Our Deploy4Performance Pipeline"
    - bash: echo "isMain-"$(isMain)
- stage: Fifth
  displayName: 'Regression Stage'
  dependsOn: Third
  condition: succeeded('Third')
  variables:
    isFourth: 'true'
  jobs:
  - job: RegressionSuiteJob
    displayName: RegressionSuite1
    variables:
      isAlways: 'true'
    steps:
    - bash: echo "Our Fourth Pipeline-StabilitySanityAfterDeploy-Always"
    - bash: echo "isAlways-"$(isAlways)
    - bash: echo "isStage1-"$(isStage1)
    - bash: echo "isFourth-"$(isFourth)
    - bash: echo "isGlobal-"$(isGlobal)
    - bash: export vAlways="vAlways";
    - bash: echo "vAlways-"$vAlways
  - job: RegressionSuite2
    dependsOn: RegressionSuiteJob
    condition: succeeded('RegressionSuiteJob')
    displayName: RegressionSuite2
    steps:
    - bash: echo "Our Fourth Pipeline-StabilitySanityAfterDeploy-Depends"
    - bash: echo "isAlways-"$(isAlways)
    - bash: echo "isStage1-"$(isStage1)
    - bash: echo "isFourth-"$(isFourth)
    - bash: echo "isGlobal-"$(isGlobal)
    - bash: echo "vAlways-"$vAlways


- stage: Sixth
  displayName: 'Provision Infra n Execute PT Stage'
  dependsOn: Fourth
  #condition: always()
  jobs:  
  - job: 'ProvisionLoadAgent'
    displayName: 'Provision Load Agent'
    steps:
    - bash: echo "Our Provision Infra Pipeline"
  - job: 'ExecuteTest'
    displayName: 'Execute Test'
    steps:
    - bash: echo "Our Provision Infra Pipeline"
  - job: 'PublishResult'
    displayName: 'Publish Result'
    steps:
    - bash: echo "Our Provision Infra Pipeline"
  - job: 'RemoveLoadAgent'
    displayName: 'Remove Provisioned Load Agent'
    steps:
    - bash: echo "Our Remove Provisioned Load Agent"

- stage: Seventh
  displayName: 'Deploy in Higher Env Stage'
  dependsOn: 
  - Sixth
  - Fifth
  condition: and(succeeded(), eq(variables.isMain, true))
  jobs:  
  - job: DeployNextEnv
    displayName: 'Deploy to Next Env'
    steps:
    - bash: echo "Our Deploy4Performance Pipeline"
    - bash: echo "isMain-"$(isMain)