trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
 
stages:
- stage: First
  displayName: First Stage
  jobs:
  - job: Firstjob
    displayName: BuildFirst
    timeoutInMinutes: 10
    steps:
    - task: Bash@3
      displayName: First echo-Dev branch
      inputs:
        targetType: 'inline'
        script: 'echo "The First job in dev branch"'
- stage: Second
  displayName: Second Stage
  dependsOn: 'First'
  jobs:  
  - job: Secondjob
    displayName: DeployAfterBuild
    steps:
    - bash: echo "Our Second Pipeline"
- stage: Third
  displayName: Third Stage
  dependsOn: Second
  jobs:  
  - job: Thirdjob
    displayName: FuncSanityAfterDeploy
    steps:
    - bash: echo "Our Third Pipeline"
- stage: Fourth
  displayName: Fourth Stage Always
  dependsOn: Second
  condition: always() 
  jobs:  
  - job: FourthJobAlways
    displayName: StabilitySanityAfterDeploy
    steps:
    - bash: echo "Our Fourth Pipeline"

- stage: OnlyMaster
  displayName: OnlyMaster Stage
  dependsOn: Second
  condition: and(succeeded(), eq(variables.isMain, true))
  jobs:  
  - job: OnlyMaster
    displayName: Sanity4Master
    steps:
    - bash: echo "Our OnlyMaster Pipeline"
    - bash: echo "isMain-"$(isMain)

- stage: Fifth
  displayName: Fifth Stage Always
  dependsOn: 
  - Third
  - Fourth
  - OnlyMaster
  #condition: always()
  jobs:  
  - job: FifthJobAlways
    displayName: FuncRegressionAfterSanity
    steps:
    - bash: echo "Our Fifth Pipeline"
